Repository UDM2C/UDM2C, pull requests merged in 2024-08, with the labels that each got.

#73 Feat/#1 결제 디버깅코드 및 사용하지않는 주석 삭제
  src/main/java/com/example/livealone/global/config/CorsConfig.java
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
  src/main/resources/application.yaml
Labels: fix, refactor

#75 Docs/#74 compose file update + nginxconf update
  build.gradle
  compose.yaml
  nginx.conf
  src/main/java/com/example/livealone/DataLoader.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/test/java/com/example/livealone/ConcurrentTest.java
  src/test/java/com/example/livealone/MockSpringSecurityFilter.java
Labels: documentation

#83 Refactor/#79 broadcast open close websocket
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/dto/StreamKeyResponseDto.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastMapper.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/global/handler/WebSocketHandler.java
Labels: refactor

#84 Refactor/#82 get broadcast
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/dto/CreateBroadcastResponseDto.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastMapper.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/order/service/OrderService.java
Labels: refactor

#85 feat: 스트리머-스트리밍-(구매하기)-결제 연결 중
  src/main/java/com/example/livealone/order/controller/OrderController.java
  src/main/java/com/example/livealone/payment/dto/PaymentRequestDto.java
  src/main/java/com/example/livealone/payment/entity/Payment.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
  src/main/java/com/example/livealone/product/controller/ProductController.java
  src/test/java/com/example/livealone/ConcurrentTest.java
  src/test/java/com/example/livealone/MockSpringSecurityFilter.java
Labels: feat, fix

#86 feat: 스트리머-스트리밍-(구매하기)-결제 연결 중
  src/main/java/com/example/livealone/DataLoader.java
  src/main/java/com/example/livealone/payment/dto/PaymentRequestDto.java
  src/main/java/com/example/livealone/payment/repository/PaymentRepository.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
Labels: feat, fix

#87 Feature/#80 aws ec2
  src/main/java/com/example/livealone/global/config/CorsConfig.java
  src/main/resources/application.yaml
Labels: feat

#88 Feature/#80 aws ec2
  src/main/java/com/example/livealone/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
Labels: fix

#90 [Move] Develop -> Release
  src/main/java/com/example/livealone/DataLoader.java
  src/main/java/com/example/livealone/global/config/CorsConfig.java
  src/main/java/com/example/livealone/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/livealone/payment/dto/PaymentRequestDto.java
  src/main/java/com/example/livealone/payment/repository/PaymentRepository.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
  src/main/resources/application.yaml
Labels: move

#91 Feat/#1 스트리머-스트리밍-(구매하기)-결제 연동
  src/main/java/com/example/livealone/payment/service/PaymentService.java
Labels: fix

#95 Fix/#89 fix chatting bug
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/handler/WebSocketHandler.java
Labels: fix

#97 Fix/#93 security api authentication
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
Labels: fix

#96 Feat/#94 create broadcast code api
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/dto/BroadcastCodeRequestDto.java
  src/main/java/com/example/livealone/broadcast/dto/BroadcastCodeResponseDto.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastCodeMapper.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastCodeRepository.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/resources/application.yaml
  src/main/resources/messages.properties
Labels: feat

#99 Feat/#80 release 최신화
  src/main/java/com/example/livealone/payment/service/PaymentService.java
Labels: fix

#101 Fix : BroadcastResponseDto 에 broadcastId와 productQuantity 추가
  src/main/java/com/example/livealone/broadcast/dto/BroadcastResponseDto.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastMapper.java
Labels: fix

#102 Refactor/#98 set uri environment variables
  compose.yaml
  src/main/java/com/example/livealone/chat/controller/ChatController.java
  src/main/java/com/example/livealone/global/config/AppConfig.java
  src/main/java/com/example/livealone/global/config/CorsConfig.java
  src/main/java/com/example/livealone/global/config/URIConfig.java
  src/main/java/com/example/livealone/global/handler/WebSocketHandler.java
  src/main/java/com/example/livealone/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
  src/main/resources/application.yaml
Labels: refactor

#103 fix: 오타수정
  src/main/java/com/example/livealone/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
Labels: fix

#105 Fix/#104 스트림 키 요청 세션한테만 전달
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/global/handler/WebSocketHandler.java
Labels: fix

#107 fix : Cors 버그 수정
  src/main/java/com/example/livealone/global/config/CorsConfig.java
  src/main/java/com/example/livealone/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
Labels: fix

#109 Fix/#108 방송 코드 16자리로 나오게
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastCodeMapper.java
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
Labels: fix

#110 fix: payment관련 cors수정
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
Labels: fix

#112 fix: 결제 관련 로그 기록 및 web security permit 변경
  src/main/java/com/example/livealone/global/security/AuthenticationEntryPointImpl.java
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
  src/main/java/com/example/livealone/global/security/filter/JwtAuthentication.java
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
Labels: fix

#113 feat: 토스페이 Order-Check컨트롤러 추가
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
Labels: feat

#116 Refactor/#115 min order quantity
  src/main/java/com/example/livealone/order/dto/OrderRequestDto.java
Labels: refactor

#118 Refactor/#117 유저 테스트를 위해 20분에 한 번 방송 종료, 방송 없을 시 default key 전달
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/resources/application.yaml
Labels: refactor

#121 Feature/#119 separation loggin level
  src/main/java/com/example/livealone/chat/controller/ChatController.java
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/handler/WebSocketHandler.java
  src/main/java/com/example/livealone/global/security/AuthenticationEntryPointImpl.java
  src/main/java/com/example/livealone/global/security/JwtService.java
  src/main/java/com/example/livealone/global/security/filter/JwtAuthentication.java
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
  src/main/resources/application.yaml
Labels: feat

#123 Refactor/#120 broadcasts_code -> reservations 로 변경
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/dto/BroadcastRequestDto.java
  src/main/java/com/example/livealone/broadcast/dto/ReservationRequestDto.java
  src/main/java/com/example/livealone/broadcast/entity/Broadcast.java
  src/main/java/com/example/livealone/broadcast/entity/Reservations.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastCodeMapper.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastMapper.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastCodeRepository.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepository.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepositoryQueryImpl.java
  src/main/java/com/example/livealone/broadcast/repository/ReservationRepository.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/resources/messages.properties
Labels: refactor

#124 Feature/#122 register admin
  http/관리자.http
  src/main/java/com/example/livealone/admin/controller/AdminController.java
  src/main/java/com/example/livealone/admin/dto/AdminRequestDto.java
  src/main/java/com/example/livealone/admin/service/AdminService.java
  src/main/java/com/example/livealone/global/security/UserDetailsImpl.java
  src/main/java/com/example/livealone/user/dto/UserInfoResponseDto.java
  src/main/java/com/example/livealone/user/entity/User.java
  src/main/java/com/example/livealone/user/entity/UserRole.java
  src/main/java/com/example/livealone/user/mapper/UserMapper.java
  src/main/java/com/example/livealone/user/service/UserService.java
  src/main/resources/application.yaml
  src/main/resources/messages.properties
Labels: feat

#127 Feature/#125 distributedlock aop
  http/관리자.http
  src/main/java/com/example/livealone/admin/controller/AdminController.java
  src/main/java/com/example/livealone/admin/dto/AdminRequestDto.java
  src/main/java/com/example/livealone/admin/service/AdminService.java
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/dto/BroadcastRequestDto.java
  src/main/java/com/example/livealone/broadcast/dto/ReservationRequestDto.java
  src/main/java/com/example/livealone/broadcast/entity/Broadcast.java
  src/main/java/com/example/livealone/broadcast/entity/Reservations.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastCodeMapper.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastMapper.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepository.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepositoryQueryImpl.java
  src/main/java/com/example/livealone/broadcast/repository/ReservationRepository.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/global/aop/AopForTransaction.java
  src/main/java/com/example/livealone/global/aop/CustomSpringELParser.java
  src/main/java/com/example/livealone/global/aop/DistributedLock.java
  src/main/java/com/example/livealone/global/aop/DistributedLockAop.java
  src/main/java/com/example/livealone/global/security/UserDetailsImpl.java
  src/main/java/com/example/livealone/order/service/OrderService.java
  src/main/java/com/example/livealone/user/dto/UserInfoResponseDto.java
  src/main/java/com/example/livealone/user/entity/User.java
  src/main/java/com/example/livealone/user/entity/UserRole.java
  src/main/java/com/example/livealone/user/mapper/UserMapper.java
  src/main/java/com/example/livealone/user/service/UserService.java
  src/main/resources/application.yaml
  src/main/resources/messages.properties
Labels: feat

#129 Feature/#128 방송 예약 api 및 이메일 발송
  build.gradle
  http/방송.http
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/dto/ReservationRequestDto.java
  src/main/java/com/example/livealone/broadcast/dto/ReservationResponseDto.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastCodeMapper.java
  src/main/java/com/example/livealone/broadcast/mapper/ReservationMapper.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/global/mail/MailConfig.java
  src/main/java/com/example/livealone/global/mail/MailService.java
  src/main/resources/application.yaml
  src/main/resources/messages.properties
Labels: feat

#131 Feat/#130 특정 날짜 방송 예약 상태 리스트 조회
  http/방송.http
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/dto/ReservationStateResponseDto.java
  src/main/java/com/example/livealone/broadcast/repository/ReservationRepository.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
Labels: feat

#132 ✨ featurer: get admin page info
  src/main/java/com/example/livealone/admin/controller/AdminController.java
  src/main/java/com/example/livealone/admin/dto/AdminBroadcastListResponseDto.java
  src/main/java/com/example/livealone/admin/dto/AdminRoleResponseDto.java
  src/main/java/com/example/livealone/admin/dto/AdminUserListResponseDto.java
  src/main/java/com/example/livealone/admin/mapper/AdminMapper.java
  src/main/java/com/example/livealone/admin/service/AdminService.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastMapper.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepository.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/user/controller/UserController.java
  src/main/java/com/example/livealone/user/mapper/UserMapper.java
  src/main/java/com/example/livealone/user/service/UserService.java
  src/main/resources/messages.properties
Labels: feat

#134 ✨ featurer/#133 Get broadcast details
  http/관리자.http
  src/main/java/com/example/livealone/admin/controller/AdminController.java
  src/main/java/com/example/livealone/admin/dto/AdminBroadcastDetailResponseDto.java
  src/main/java/com/example/livealone/admin/mapper/AdminMapper.java
  src/main/java/com/example/livealone/admin/service/AdminService.java
  src/main/java/com/example/livealone/order/repository/OrderRepository.java
  src/main/java/com/example/livealone/order/repository/OrderRepositoryQuery.java
  src/main/java/com/example/livealone/order/repository/OrderRepositoryQueryImpl.java
  src/main/java/com/example/livealone/order/service/OrderService.java
Labels: feat

#137 Feature/#136 delete order after ten minutes
  src/main/java/com/example/livealone/order/controller/OrderController.java
  src/main/java/com/example/livealone/order/repository/OrderRepositoryQuery.java
  src/main/java/com/example/livealone/order/repository/OrderRepositoryQueryImpl.java
  src/main/java/com/example/livealone/order/service/OrderService.java
  src/main/resources/messages.properties
Labels: feat

#138 Feature/#135 get user payment list in broadcast
  http/관리자.http
  src/main/java/com/example/livealone/admin/controller/AdminController.java
  src/main/java/com/example/livealone/admin/dto/AdminConsumerResponseDto.java
  src/main/java/com/example/livealone/admin/mapper/AdminMapper.java
  src/main/java/com/example/livealone/admin/service/AdminService.java
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/dto/BroadcastTitleResponseDto.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastMapper.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/order/repository/OrderRepository.java
  src/main/java/com/example/livealone/order/repository/OrderRepositoryQuery.java
  src/main/java/com/example/livealone/order/repository/OrderRepositoryQueryImpl.java
  src/main/java/com/example/livealone/order/service/OrderService.java
Labels: feat

#141 Feature/#82 주문내역 조회기능 추가 & 결제 취소 시 동작 수정 & 토스페이 결제 완료 상태 수정
  http/방송.http
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/dto/PaymentResponseDto.java
  src/main/java/com/example/livealone/payment/entity/Payment.java
  src/main/java/com/example/livealone/payment/entity/PaymentStatus.java
  src/main/java/com/example/livealone/payment/repository/PaymentRepository.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
  src/main/resources/application.yaml
Labels: feat, fix

#144 Fix : Login Redirect url 환경변수 설정
  src/main/java/com/example/livealone/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/resources/application.yaml
Labels: fix

#147 Fix/#142 main use redis
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/delivery/service/DeliveryService.java
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
  src/main/java/com/example/livealone/product/service/ProductService.java
  src/main/java/com/example/livealone/user/service/UserService.java
Labels: fix

#148 Feature/#114 chat service
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/chat/controller/ChatController.java
  src/main/java/com/example/livealone/chat/dto/ChatDto.java
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/config/StompHandler.java
  src/main/java/com/example/livealone/global/config/WebSocketConfig.java
  src/main/java/com/example/livealone/global/handler/WebSocketHandler.java
Labels: feat

#151 Feature/#150 http protocol env and alert
  src/main/java/com/example/livealone/alert/service/AlertService.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/global/config/CorsConfig.java
  src/main/java/com/example/livealone/global/entity/SocketMessageType.java
  src/main/java/com/example/livealone/order/controller/OrderController.java
  src/main/java/com/example/livealone/order/dto/OrderQuantityResponseDto.java
  src/main/java/com/example/livealone/order/mapper/OrderMapper.java
  src/main/java/com/example/livealone/order/service/OrderService.java
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
  src/main/java/com/example/livealone/product/entity/Product.java
  src/main/resources/application.yaml
Labels: feat, refactor

#153 Fix/#152 server_host https -> http
  src/main/resources/application.yaml
Labels: fix

#154 Fix/#152 order check err
  src/main/java/com/example/livealone/order/service/OrderService.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
  src/main/java/com/example/livealone/product/entity/Product.java
Labels: fix

#156 Fix#155 방송 시작, 종료 안 되는 버그
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
Labels: fix

#158 Refactor/#157 check admin in filter
  http/관리자.http
  src/main/java/com/example/livealone/admin/controller/AdminController.java
  src/main/java/com/example/livealone/admin/service/AdminService.java
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
Labels: refactor

#159 feat: 실시간 시청자 수 표시 기능 추가
  src/main/java/com/example/livealone/chat/controller/ChatController.java
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/config/StompHandler.java
  src/main/java/com/example/livealone/global/entity/SocketMessageType.java
Labels: feat

#161 feat: ALB적용을 위한 엔드포인트 설정, 컨트롤러 설정, yml파일 변경
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/controller/LoadBallancerController.java
  src/main/java/com/example/livealone/global/exception/ExceptionResponseDto.java
  src/main/java/com/example/livealone/global/security/AuthenticationEntryPointImpl.java
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
  src/main/java/com/example/livealone/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/livealone/oauth2/service/Oauth2UserServiceImpl.java
  src/main/resources/application.yaml
Labels: feat

#163 Fix/#162 set envirotment variables
  src/main/java/com/example/livealone/global/config/KafkaConsumerConfig.java
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
  src/main/resources/application.yaml
Labels: fix

#164 Fix/#82 디폴트 방송 상태 수정
  src/main/resources/messages.properties
Labels: fix

#165 Feature/#114 chat service
  src/main/java/com/example/livealone/chat/dto/ChatDto.java
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/security/JwtService.java
Labels: feat

#169 Fix/#166 Get History Err
  src/main/java/com/example/livealone/admin/controller/AdminController.java
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/delivery/controller/DeliveryController.java
  src/main/java/com/example/livealone/delivery/service/DeliveryService.java
Labels: fix

#168 Refactor/#167 방송 예약할 때 다른 예약 잡아놓은 거 있는지 확인
  src/main/java/com/example/livealone/reservation/repository/ReservationRepository.java
  src/main/java/com/example/livealone/reservation/service/ReservationService.java
  src/main/resources/messages.properties
Labels: refactor

#171 Refactor/#170 mypage add total sale price
  http/관리자.http
  http/방송.http
  http/유저.http
  src/main/java/com/example/livealone/broadcast/dto/UserBroadcastResponseDto.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepositoryQueryImpl.java
Labels: refactor

#173 Docs/#172 create readme
  README.md
Labels: documentation

#174 Feature/#114 chat service
  src/main/java/com/example/livealone/chat/controller/ChatController.java
  src/main/java/com/example/livealone/chat/dto/ChatChannelBoundDto.java
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/config/StompHandler.java
  src/main/java/com/example/livealone/global/entity/SocketMessageType.java
Labels: feat

#175 feat: 실시간 시청자 수 제거
  src/main/java/com/example/livealone/chat/controller/ChatController.java
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/config/StompHandler.java
Labels: feat

#176 feat: 로그인을 하지 않아도 채팅 초기화
  src/main/java/com/example/livealone/chat/service/ChatService.java
Labels: feat

#178 refactor: 필요없는 코드 제거
  src/main/java/com/example/livealone/chat/dto/ChatChannelBoundDto.java
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/config/StompHandler.java
  src/main/java/com/example/livealone/global/config/WebSocketConfig.java
Labels: refactor

#179 Fix: mypage input valueable edit
  src/main/java/com/example/livealone/user/dto/UserInfoRequestDto.java
Labels: fix

#181 Docs/#180 update readme
  README.md
Labels: documentation

#183 Fix/#182 방송 내역 조회 page로
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepositoryQuery.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepositoryQueryImpl.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
Labels: fix

#185 Fix /#82 주문내역에 페이지네이션 추가
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/dto/PaymentHistoryDto.java
  src/main/java/com/example/livealone/payment/repository/PaymentRepository.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
Labels: fix

#186 Feature/#82 주문내역 페이지네이션 수정
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
Labels: fix

#187 Fix/#184 get delivery info for page
  src/main/java/com/example/livealone/delivery/controller/DeliveryController.java
  src/main/java/com/example/livealone/delivery/service/DeliveryService.java
  src/main/java/com/example/livealone/user/repository/UserRepositoryQuery.java
  src/main/java/com/example/livealone/user/repository/UserRepositoryQueryImpl.java
Labels: fix

#188 Fix /#82 주문내역에 페이지네이션 버그수정
  src/main/java/com/example/livealone/payment/dto/PaymentHistoryDto.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
Labels: fix

#189 Fix/#82 주문내역 버그수정완료
  http/유저.http
  src/main/java/com/example/livealone/payment/dto/PaymentHistoryDto.java
  src/main/java/com/example/livealone/payment/dto/PaymentInfoDto.java
  src/main/java/com/example/livealone/payment/repository/PaymentRepository.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
Labels: fix
