Repository UDM2C/UDM2C, pull requests merged in 2024-07, with the labels that each got.

#4 Refactor/#2 broadcast fk setting
  src/main/java/com/example/livealone/broadcast/entity/Broadcast.java
  src/main/java/com/example/livealone/broadcast/entity/BroadcastCode.java
Labels: fix

#7 Feat/#5 Create broadcast
  build.gradle
  http/방송.http
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/dto/BroadcastRequestDto.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastMapper.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastCodeRepository.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepository.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/order/entity/Order.java
  src/main/java/com/example/livealone/user/entity/User.java
  src/main/resources/application.yaml
  src/main/resources/messages.properties
Labels: feat

#8 ✨ feature: feature/#3 상품 등록 기능 구현
  src/main/java/com/example/livealone/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/livealone/product/controller/ProductController.java
  src/main/java/com/example/livealone/product/dto/ProductRequestDto.java
  src/main/java/com/example/livealone/product/dto/ProductResponseDto.java
  src/main/java/com/example/livealone/product/entity/Product.java
  src/main/java/com/example/livealone/product/service/ProductService.java
Labels: feat

#12 Feature/#10 feat inquiry userinfo
  src/main/java/com/example/livealone/global/security/UserDetailsImpl.java
  src/main/java/com/example/livealone/user/controller/UserController.java
  src/main/java/com/example/livealone/user/dto/UserInfoDto.java
  src/main/java/com/example/livealone/user/mapper/UserMapper.java
  src/main/java/com/example/livealone/user/service/UserService.java
  src/main/resources/application.yaml
  src/main/resources/messages.properties
Labels: feat

#16 ✨ Feature/#11 유저 방송 내역 조회 기능 구현
  build.gradle
  http/방송.http
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/dto/BroadcastResponseDto.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepository.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepositoryQuery.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepositoryQueryImpl.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/global/config/JPAConfig.java
Labels: feat, fix

#14 ✨ Feature/#9 inquiry product
  src/main/java/com/example/livealone/product/controller/ProductController.java
  src/main/java/com/example/livealone/product/dto/ProductRequestDto.java
  src/main/java/com/example/livealone/product/dto/ProductResponseDto.java
  src/main/java/com/example/livealone/product/entity/Product.java
  src/main/java/com/example/livealone/product/mapper/ProductMapper.java
  src/main/java/com/example/livealone/product/service/ProductService.java
Labels: feat, fix

#20 Feature/#2 kakaopay & tosspay
  src/main/java/com/example/livealone/LivealoneApplication.java
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/entity/Payment.java
  src/main/java/com/example/livealone/payment/entity/PaymentStatus.java
  src/main/java/com/example/livealone/payment/repository/PaymentRepository.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
  src/main/resources/application.yaml
Labels: feat

#22 Fix/#15 UserBroadcastResponseDto 생성 후 수정
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/dto/BroadcastResponseDto.java
  src/main/java/com/example/livealone/broadcast/dto/UserBroadcastResponseDto.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepositoryQuery.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepositoryQueryImpl.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
Labels: fix

#24 Feature/#23 방송 중단 API 구현
  http/방송.http
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/entity/Broadcast.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
Labels: feat

#25 Feature/#18 inquiry user delivery history
  src/main/java/com/example/livealone/delivery/controller/DeliveryController.java
  src/main/java/com/example/livealone/delivery/dto/DeliveryHistoryResponseDto.java
  src/main/java/com/example/livealone/delivery/mapper/DeliveryMapper.java
  src/main/java/com/example/livealone/delivery/service/DeliveryService.java
  src/main/java/com/example/livealone/user/mapper/UserMapper.java
  src/main/java/com/example/livealone/user/repository/UserRepository.java
  src/main/java/com/example/livealone/user/repository/UserRepositoryQuery.java
  src/main/java/com/example/livealone/user/repository/UserRepositoryQueryImpl.java
  src/test/java/com/example/livealone/LivealoneApplicationTests.java
Labels: feat

#27 Fix : 소셜 로그인 버그 픽스
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
  src/main/java/com/example/livealone/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/livealone/oauth2/service/Oauth2UserServiceImpl.java
  src/main/java/com/example/livealone/oauth2/userinfo/KakaoOAuth2Userinfo.java
  src/main/java/com/example/livealone/user/entity/Social.java
  src/main/resources/application.yaml
Labels: fix

#30 feat/#29-social-login-cors
  src/main/java/com/example/livealone/global/config/CorsConfig.java
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
  src/main/java/com/example/livealone/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
Labels: feat

#28 Feature/#6 socketchat
  build.gradle
  src/main/java/com/example/livealone/chat/controller/ChatController.java
  src/main/java/com/example/livealone/chat/handler/WebSocketHandler.java
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/config/KafkaConsumerConfig.java
  src/main/java/com/example/livealone/global/config/KafkaProducerConfig.java
  src/main/java/com/example/livealone/global/config/WebSocketConfig.java
  src/main/resources/application.yaml
Labels: feat

#33 Fix/#32 google scope fix
  src/main/resources/application.yaml
Labels: fix

#35 Refactor/#34-detail-delivery-history-paging
  src/main/java/com/example/livealone/delivery/controller/DeliveryController.java
  src/main/java/com/example/livealone/delivery/service/DeliveryService.java
  src/main/java/com/example/livealone/user/repository/UserRepositoryQuery.java
  src/main/java/com/example/livealone/user/repository/UserRepositoryQueryImpl.java
Labels: refactor

#37 Fix/# 36 jwt add nickname
  src/main/java/com/example/livealone/global/security/JwtService.java
  src/main/java/com/example/livealone/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/livealone/oauth2/service/Oauth2UserServiceImpl.java
Labels: fix

#41 refactor/#39 ProductController에 유저 인증 기능 추가
  http/상품.http
  src/main/java/com/example/livealone/delivery/controller/DeliveryController.java
  src/main/java/com/example/livealone/delivery/dto/DeliveryHistoryResponseDto.java
  src/main/java/com/example/livealone/product/controller/ProductController.java
  src/main/java/com/example/livealone/product/service/ProductService.java
Labels: fix

#40 Refactor/#38 broadcast use principal
  http/방송.http
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/entity/Broadcast.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepository.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepositoryQuery.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastRepositoryQueryImpl.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/global/security/AuthenticationEntryPointImpl.java
  src/main/java/com/example/livealone/global/security/JwtService.java
Labels: refactor

#43 Feature/#42 시큐리티 api 접근 제한 설정
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
Labels: feat

#46 Feature/#6 socketchat
  build.gradle
  src/main/java/com/example/livealone/chat/controller/ChatController.java
  src/main/java/com/example/livealone/chat/dto/ChatMessage.java
  src/main/java/com/example/livealone/chat/handler/WebSocketHandler.java
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/security/JwtService.java
Labels: feat

#45 Fix/#44 broadcast restart
  src/main/java/com/example/livealone/broadcast/entity/Broadcast.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/global/config/CorsConfig.java
Labels: fix

#48 Fix/#47 deliveryuser dummy data to real data
  src/main/java/com/example/livealone/delivery/controller/DeliveryController.java
  src/main/java/com/example/livealone/delivery/service/DeliveryService.java
  src/main/java/com/example/livealone/user/controller/UserController.java
  src/main/java/com/example/livealone/user/service/UserService.java
Labels: fix

#50 refactor/#49 get broadcast & product
  http/방송.http
  src/main/java/com/example/livealone/broadcast/dto/BroadcastResponseDto.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastMapper.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/product/controller/ProductController.java
  src/main/java/com/example/livealone/product/service/ProductService.java
Labels: refactor

#54 Feature/#53 redis setup
  build.gradle
  compose.yaml
  src/main/java/com/example/livealone/global/config/RedisConfig.java
  src/main/java/com/example/livealone/global/config/RedissonConfig.java
  src/main/resources/application.yaml
Labels: feat

#56 Feature/#52 redis cache
  src/main/java/com/example/livealone/product/mapper/ProductMapper.java
  src/main/java/com/example/livealone/product/service/ProductService.java
  src/main/java/com/example/livealone/user/service/UserService.java
Labels: feat

#58 Feature/#51 refresh redis
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
  src/main/java/com/example/livealone/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/livealone/user/controller/AuthController.java
  src/main/java/com/example/livealone/user/dto/ReissueRequestDto.java
  src/main/java/com/example/livealone/user/dto/TokenResponseDto.java
  src/main/java/com/example/livealone/user/entity/RefreshToken.java
  src/main/java/com/example/livealone/user/repository/RefreshTokenRepository.java
  src/main/java/com/example/livealone/user/service/AuthService.java
  src/main/resources/messages.properties
Labels: feat

#60 Feature/#57 get default address
  http/유저.http
  src/main/java/com/example/livealone/user/controller/UserController.java
  src/main/java/com/example/livealone/user/dto/UserAddressResponseDto.java
  src/main/java/com/example/livealone/user/mapper/UserMapper.java
  src/main/java/com/example/livealone/user/service/UserService.java
  src/main/resources/messages.properties
Labels: feat

#63 Feature/#61 redis cache get delivery
  src/main/java/com/example/livealone/delivery/service/DeliveryService.java
  src/main/java/com/example/livealone/user/repository/UserRepositoryQueryImpl.java
Labels: feat

#64 Feat/#55 chat logger
  build.gradle
  compose.yaml
  src/main/java/com/example/livealone/chat/controller/ChatController.java
  src/main/java/com/example/livealone/chat/dto/ChatDto.java
  src/main/java/com/example/livealone/chat/dto/ChatInitDto.java
  src/main/java/com/example/livealone/chat/entity/ChatErrorLog.java
  src/main/java/com/example/livealone/chat/entity/ChatMessage.java
  src/main/java/com/example/livealone/chat/entity/ChatMessageType.java
  src/main/java/com/example/livealone/chat/entity/ChatSessionLog.java
  src/main/java/com/example/livealone/chat/handler/ChatShutdownHandler.java
  src/main/java/com/example/livealone/chat/handler/WebSocketHandler.java
  src/main/java/com/example/livealone/chat/repository/ChatErrorLogRepository.java
  src/main/java/com/example/livealone/chat/repository/ChatMessageRepository.java
  src/main/java/com/example/livealone/chat/repository/ChatSessionLogRepository.java
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/resources/application.yaml
Labels: feat

#65 Feature/#59 redis concurrent control
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/java/com/example/livealone/global/config/RedissonConfig.java
  src/main/java/com/example/livealone/order/controller/OrderController.java
  src/main/java/com/example/livealone/order/dto/OrderRequestDto.java
  src/main/java/com/example/livealone/order/dto/OrderResponseDto.java
  src/main/java/com/example/livealone/order/repository/OrderRepository.java
  src/main/java/com/example/livealone/order/service/OrderService.java
  src/main/java/com/example/livealone/product/entity/Product.java
  src/main/java/com/example/livealone/product/service/ProductService.java
  src/main/resources/messages.properties
  src/test/java/com/example/livealone/ConcurrentTest.java
Labels: feat

#66 Feature/#1 카카오 결제 구현 완료/토스창 붙임 완료
  build.gradle
  src/main/java/com/example/livealone/DataLoader.java
  src/main/java/com/example/livealone/LivealoneApplication.java
  src/main/java/com/example/livealone/broadcast/entity/BroadcastCode.java
  src/main/java/com/example/livealone/global/config/AppConfig.java
  src/main/java/com/example/livealone/order/entity/Order.java
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/dto/PaymentResponseDto.java
  src/main/java/com/example/livealone/payment/repository/PaymentRepository.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
  src/main/java/com/example/livealone/product/entity/Product.java
  src/main/java/com/example/livealone/user/repository/UserRepository.java
  src/main/resources/application.yaml
Labels: feat

#68 refactor: WebSocket 전역화
  src/main/java/com/example/livealone/chat/controller/ChatController.java
  src/main/java/com/example/livealone/chat/dto/ChatDto.java
  src/main/java/com/example/livealone/chat/entity/ChatErrorLog.java
  src/main/java/com/example/livealone/chat/entity/ChatMessageType.java
  src/main/java/com/example/livealone/chat/entity/ChatSessionLog.java
  src/main/java/com/example/livealone/chat/handler/WebSocketHandler.java
  src/main/java/com/example/livealone/chat/service/ChatService.java
  src/main/java/com/example/livealone/global/config/WebSocketConfig.java
  src/main/java/com/example/livealone/global/dto/SocketMessageDto.java
  src/main/java/com/example/livealone/global/entity/SocketMessageType.java
  src/main/java/com/example/livealone/global/handler/WebSocketHandler.java
Labels: refactor

#70 Feature/#1 토스페이 백엔드 구현완료
  src/main/java/com/example/livealone/global/security/config/WebSecurityConfig.java
  src/main/java/com/example/livealone/payment/controller/PaymentController.java
  src/main/java/com/example/livealone/payment/service/PaymentService.java
  src/main/resources/application.yaml
Labels: feat

#72 Feature/#62 streamKey web socket
  http/방송.http
  src/main/java/com/example/livealone/broadcast/controller/BroadcastController.java
  src/main/java/com/example/livealone/broadcast/dto/StreamKeyResponseDto.java
  src/main/java/com/example/livealone/broadcast/mapper/BroadcastMapper.java
  src/main/java/com/example/livealone/broadcast/repository/BroadcastCodeRepository.java
  src/main/java/com/example/livealone/broadcast/service/BroadcastService.java
  src/main/resources/messages.properties
Labels: feat
